### ISSUE TITLE
How do I set this up?

### ISSUE THREAD

**Issue by bamtan** [jonas747/discordlfm#1]
After running `./main.go -t "my secret discord token" -l "my secret last.fm api key" -u "lastfmusername" ` i get the following: 

```
./main.go: line 1: package: command not found
./main.go: line 3: syntax error near unexpected token `newline'
./main.go: line 3: `import ('
```

**Comment by jonas747** [comment]
you have to compile it using go

**Comment by bamtan** [comment]
Ah, thanks! I'm getting the correct console output now. 

Any idea how I can add the .exe to my Games?

**Comment by jonas747** [comment]
hmm what do you mean?

**Comment by bamtan** [comment]
Discord doesn't detect the .exe in my Games tab in settings. The .exe is running in the process as seen in task manager though.

**Comment by jonas747** [comment]
nicenice
