### ISSUE TITLE
install instructions?

### ISSUE THREAD

**Issue by hamishmaku** [jonas747/discordlfm#7]
hoi, I'd really like to get this set up, but I don't know how to use it? I can get my last.fm api key and discord key value, but I don't know how to execute the script?

halp! thanks!

**Comment by jonas747** [comment]
i compiled it for some platforms and made a release https://github.com/jonas747/discordlfm/releases

**Comment by hamishmaku** [comment]
thanks! that works great.

appreciate your work.
